# Generated by Django 5.2.17 on 2026-09-04 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_blogpost_category_remove_comment_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={},
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='created_at',
        ),
    ]
